### ISSUE TITLE
Error in installing requirements...

### ISSUE THREAD

**Issue by YukiRainee** [Cog-Creators/Red-DiscordBot#795]
So error occurs when attempting to install the requirements but errors out when it can't (along with a upgrade pip to 9.0.1 warning) now when attempting to launch redbot it works but only with 10-11 cogs active. Now I'm just wondering do I have to worry about that error right there or am I good to go?

`Collecting pip (from -r requirements.txt (line 1))
  Using cached pip-9.0.1-py2.py3-none-any.whl
Collecting discord.py[voice] from git+git://github.com/Rapptz/discord.py.git#egg=discord.py[voice] (from -r requirements.txt (line 2))
  Cloning git://github.com/Rapptz/discord.py.git to /tmp/pip-build-ltb2xy4t/discord.py
Collecting youtube_dl (from -r requirements.txt (line 3))
  Using cached youtube_dl-2017.6.5-py2.py3-none-any.whl
Collecting imgurpython (from -r requirements.txt (line 4))
Collecting aiohttp<1.1.0,>=1.0.0 (from discord.py[voice]->-r requirements.txt (line 2))
  Using cached aiohttp-1.0.5-cp35-cp35m-manylinux1_x86_64.whl
Collecting websockets<4.0,>=3.1 (from discord.py[voice]->-r requirements.txt (line 2))
  Using cached websockets-3.3-py33.py34.py35.py36-none-any.whl
Collecting PyNaCl==1.0.1 (from discord.py[voice]->-r requirements.txt (line 2))
Collecting requests (from imgurpython->-r requirements.txt (line 4))
  Using cached requests-2.17.3-py2.py3-none-any.whl
Collecting multidict>=2.0 (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]->-r requirements.txt (line 2))
  Using cached multidict-2.1.6-cp35-cp35m-manylinux1_x86_64.whl
Collecting async-timeout (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]->-r requirements.txt (line 2))
  Using cached async_timeout-1.2.1-py3-none-any.whl
Collecting chardet (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]->-r requirements.txt (line 2))
  Using cached chardet-3.0.3-py2.py3-none-any.whl
Collecting six (from PyNaCl==1.0.1->discord.py[voice]->-r requirements.txt (line 2))
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting cffi>=1.1.0 (from PyNaCl==1.0.1->discord.py[voice]->-r requirements.txt (line 2))
  Using cached cffi-1.10.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting certifi>=2017.4.17 (from requests->imgurpython->-r requirements.txt (line 4))
  Using cached certifi-2017.4.17-py2.py3-none-any.whl
Collecting urllib3<1.22,>=1.21.1 (from requests->imgurpython->-r requirements.txt (line 4))
  Using cached urllib3-1.21.1-py2.py3-none-any.whl
Collecting idna<2.6,>=2.5 (from requests->imgurpython->-r requirements.txt (line 4))
  Using cached idna-2.5-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.1.0->PyNaCl==1.0.1->discord.py[voice]->-r requirements.txt (line 2))
Installing collected packages: pip, multidict, async-timeout, chardet, aiohttp, websockets, six, pycparser, cffi, PyNaCl, discord.py, youtube-dl, certifi, urllib3, idna, requests, imgurpython
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 335, in run
    prefix=options.prefix_path,
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 732, in install
    **kwargs
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 837, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1039, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/usr/lib/python3/dist-packages/pip/locations.py", line 153, in distutils_scheme
    i.finalize_options()
  File "/usr/share/python-wheels/setuptools-20.7.0-py2.py3-none-any.whl/setuptools/command/install.py", line 38, in finalize_options
    orig.install.finalize_options(self)
  File "/usr/lib/python3.5/distutils/command/install.py", line 273, in finalize_options
    raise DistutilsOptionError("can't combine user with prefix, "
distutils.errors.DistutilsOptionError: can't combine user with prefix, exec_prefix/home, or install_(plat)base
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

An error occurred and the requirements setup might not be completed. Consult the docs.

`

**Comment by pgaetani** [comment]
Corrected by upgrading pip as the error says. 
'pip install --upgrade pip'

**Comment by YukiRainee** [comment]
was only able to upgrade to 8.1.1 cant upgrade to the latest one and the error still occurs

**Comment by pgaetani** [comment]
Post the error or a screenshot of how you tried to upgrade pip, because there is no other way to fix that error other than upgrading pip.

**Comment by YukiRainee** [comment]
nvm managed to fix it turns out I had turned into one of those users from tfts for a bit *facedesk* had python2.7 from the image installed removed it and updated pip turns out I was also using pip instead of pip3 *sigh*
